FROM kasmweb/core-ubuntu-focal:1.13.0
USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
ENV INST_SCRIPTS $STARTUPDIR/install
WORKDIR $HOME


######### Customize Container Here ###########

#Install Git
RUN apt-get update && \
apt-get install git -y

##SPIDERFOOT
#configure logontracer
RUN apt-get install python3-pip -y
RUN git clone https://github.com/smicallef/spiderfoot.git \
    && pip3 install -r spiderfoot/requirements.txt 

# Create persistent folders
ENV SPIDERFOOT_DATA /var/lib/spiderfoot
ENV SPIDERFOOT_LOGS /var/lib/spiderfoot/log
ENV SPIDERFOOT_CACHE /var/lib/spiderfoot/cache
RUN mkdir -p $SPIDERFOOT_DATA || true \
    && mkdir -p $SPIDERFOOT_LOGS || true \
    && mkdir -p $SPIDERFOOT_CACHE || true \
    && chown 1000:0 $SPIDERFOOT_DATA \
    && chown 1000:0 $SPIDERFOOT_LOGS \
    && chown 1000:0 $SPIDERFOOT_CACHE

# Clean up
RUN apt-get clean &&\
    apt-get clean autoclean &&\
    apt-get autoremove -y &&\
    rm -rf /tmp/* &&\
    rm -rf /var/lib/{apt,dpkg,cache,log}/

##Startup-Script
ENV START_SCRIPT Custom_Images_Kasm/Spiderfoot-Kasm/
COPY $START_SCRIPT/startup.sh /home/kasm-user/startup.sh
RUN chmod +x /home/kasm-user/startup.sh
RUN echo "/usr/bin/desktop_ready && /home/kasm-user/startup.sh" > $STARTUPDIR/custom_startup.sh \
&& chmod +x $STARTUPDIR/custom_startup.sh



# Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/
# Update the desktop environment to be optimized for a single application
RUN cp $HOME/.config/xfce4/xfconf/single-application-xfce-perchannel-xml/* $HOME/.config/xfce4/xfconf/xfce-perchannel-xml/
RUN cp /usr/share/extra/backgrounds/bg_kasm.png /usr/share/extra/backgrounds/bg_default.png
RUN apt-get remove -y xfce4-panel
# Setup the custom startup script that will be invoked when the container starts
ENV LAUNCH_URL  http://localhost:5001
ENV KASM_RESTRICTED_FILE_CHOOSER=1


#Startup-Script
ENV START_SCRIPT Custom_Images_Kasm/Spiderfoot-Kasm/
COPY $START_SCRIPT/startup.sh $STARTUPDIR/startup.sh
RUN echo "sh /dockerstartup/startup.sh" > $STARTUPDIR/custom_startup.sh \
&& chown 1000:0 $STARTUPDIR/custom_startup.sh \
&& chmod +x $STARTUPDIR/custom_startup.sh

######### End Customizations ###########

RUN chown 1000:0 $HOME
RUN $STARTUPDIR/set_user_permission.sh $HOME

ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 1000:0 $HOME

USER 1000
