ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG

USER root

ENV HOME /home/kasm-default-profile
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME


### Envrionment config
ENV DEBIAN_FRONTEND noninteractive
ENV KASM_RX_HOME $STARTUPDIR/kasmrx
ENV INST_SCRIPTS $STARTUPDIR/install



### Install Tools
# Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/
#Install Git
RUN apt-get install git -y 



RUN wget https://github.com/sans-dfir/sift-cli/releases/latest/download/sift-cli-linux && \
    wget https://github.com/sans-dfir/sift-cli/releases/latest/download/sift-cli-linux.sig && \
    wget https://github.com/sans-dfir/sift-cli/releases/latest/download/sift-cli.pub && \
    wget https://github.com/sigstore/cosign/releases/download/v2.0.0/cosign_2.0.0_amd64.deb && \
    dpkg -i cosign_2.0.0_amd64.deb && \
    apt-get update && \
    cosign verify-blob --key sift-cli.pub --signature sift-cli-linux.sig sift-cli-linux && \
    mv sift-cli-linux /usr/local/bin/sift && \
    chmod 755 /usr/local/bin/sift 

RUN sift install



#Permissions
RUN $STARTUPDIR/set_user_permission.sh $HOME
RUN chown 0:0 $HOME
ENV HOME /home/kasm-user
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R 0:0 $HOME

USER 0

CMD ["--tail-log"]
