ARG BASE_TAG="develop"
ARG BASE_IMAGE="core-ubuntu-focal"
ARG CAST_VERSION=v0.14.0
ARG SIFT_USER=sansforensics
ARG SIFT_DESCRIPTION="SANSForensics User"
ARG SIFT_PASSWORD="forensics"
FROM kasmweb/$BASE_IMAGE:$BASE_TAG

USER root

ENV HOME /home/sansforensics
ENV STARTUPDIR /dockerstartup
WORKDIR $HOME


### Envrionment config
ENV DEBIAN_FRONTEND noninteractive
ENV KASM_RX_HOME $STARTUPDIR/kasmrx
ENV INST_SCRIPTS $STARTUPDIR/install



### Install Tools
# Install Firefox
COPY ./src/ubuntu/install/firefox/ $INST_SCRIPTS/firefox/
COPY ./src/ubuntu/install/firefox/firefox.desktop $HOME/Desktop/
RUN bash $INST_SCRIPTS/firefox/install_firefox.sh && rm -rf $INST_SCRIPTS/firefox/
#Install Git
RUN apt-get install git -y 

###
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y wget gnupg git curl sudo openssh-server && \
    groupadd -r ${SIFT_USER} && \
    useradd -r -g ${SIFT_USER} -d /home/${SIFT_USER} -s /bin/bash -c "${SIFT_DESCRIPTION}" ${SIFT_USER} && \
    mkdir /home/${SIFT_USER} && \
    usermod -a -G sudo ${SIFT_USER} && \
    echo "${SIFT_USER}:${SIFT_PASSWORD}" | chpasswd && \
    curl -Lo /tmp/cast_${CAST_VERSION}_linux_amd64.deb https://github.com/ekristen/cast/releases/download/${CAST_VERSION}/cast_${CAST_VERSION}_linux_amd64.deb && \
    apt-get install /tmp/cast_${CAST_VERSION}_linux_amd64.deb -y
###
USER ${SIFT_USER}

RUN echo ${SIFT_PASSWORD} | sudo -S cast install --mode=server teamdfir/sift-saltstack
###
USER root
RUN echo "UseDNS no" >> /etc/ssh/sshd_config && \
    echo "GSSAPIAuthentication no" >> /etc/ssh/sshd_config && \
    echo "PrintLastLog yes" >> /etc/ssh/sshd_config && \
    echo "TCPKeepAlive yes" >> /etc/ssh/sshd_config && \
    echo "X11DisplayOffset 10" >> /etc/ssh/sshd_config && \
    echo "X11UseLocalhost no" >> /etc/ssh/sshd_config && \
    git clone https://github.com/digitalsleuth/color_ssh_terminal /tmp/colorssh && \
    cd /tmp/colorssh && cat color_ssh_terminal >> /home/${SIFT_USER}/.bashrc && cd /tmp && rm -rf colorssh && \
    echo source .bashrc >> /home/${SIFT_USER}/.bash_profile && \
    chown -R ${SIFT_USER}:${SIFT_USER} /home/${SIFT_USER} && \
    apt-get autoremove -y && apt-get purge && apt-get clean && \
    rm -rf /srv && \
    rm -rf /var/cache/salt/* && \
    rm -rf /root/.cache/* && \
    unset DEBIAN_FRONTEND

#Permissions
RUN $STARTUPDIR/set_user_permission.sh $HOME
RUN chown sansforensics:sansforensics $HOME
ENV HOME /home/sansforensics
WORKDIR $HOME
RUN mkdir -p $HOME && chown -R sansforensics:sansforensics $HOME

USER sansforensics

CMD ["--tail-log"]
